name: Bun Tests

env:
  VERSION: v1.10.2

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
jobs:
  bun_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run unit tests
        run: bun test
      - name: Run typechecker
        run: bun run typecheck
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bun-report
          path: bun-report/
          retention-days: 30
